spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
springdoc:
  swagger-ui:
    path: swagger-ui.html
    operationsSorter: method
